spring:
  application:
    name: REVIEW-SERVICE

  datasource:
    url: jdbc:mariadb://localhost:3306/review_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      max-request-size: 10MB

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG