spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mariadb://localhost:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyentruongan0610@gmail.com
    password: njehntdgsveweffi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

jwt:
  secret: jW9sR7p1dQc4TfXuEzN6BvLgKa2MhZcVrW0XyAjKl9DsRuBnFxGvTyPnQzLtYkMi
  access:
    expiration: 3600000
  refresh:
    expiration: 86400000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG


cloudinary:
  cloud_name: dzwjgfd7t
  api_key: 526411628189671
  api_secret: ZtrL-STYHdMSCxaASgrQ1RGrUUY
