spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mariadb://localhost:3306/tour_booking_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
          CharSet: utf8mb4
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyentruongan0610@gmail.com
    password: njehntdgsveweffi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true