spring:
  application:
    name: BLOG-SERVICE

  datasource:
    url: jdbc:mariadb://localhost:3306/blog_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG


cloudinary:
  cloud_name: dzwjgfd7t
  api_key: 526411628189671
  api_secret: ZtrL-STYHdMSCxaASgrQ1RGrUUY