spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mariadb://localhost:3306/payment_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
          CharSet: utf8mb4
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8086
