server:
  port: 8088


spring:
  application:
    name: CHATBOT-SERVICE
  datasource:
    url: jdbc:mariadb://localhost:3306/chatbot_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG

# config connect rasa
chatbox:
  server:
    url: http://host.docker.internal:5000/query


