server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=1
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/reviews/**
          filters:
            - StripPrefix=1
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
              - Path=/api/users/**
          filters:
              - StripPrefix=1
        - id: blog-service
          uri: lb://BLOG-SERVICE
          predicates:
              - Path=/api/blog/**
          filters:
              - StripPrefix=1

  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true