spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tourDuLich
    username: root
    password: sapassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true